### ISSUE TITLE
The node could not connect to the arm.

### ISSUE THREAD

**Issue by BourliEftychia** [Sungwwoo/jackal_kinova_simulator#1]
Good evening,
I am trying to install the Jackal-kinova robot. I followed the instructions and all the packages were installed without any problem 
I managed to communicate with jackal with a script in python3 and shift him to the desired position. However when I try to run  : roslaunch kortex_driver kortex_driver.launch

[ WARN] [1696944754.215866187]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
There was a problem connecting to the server. Aborting
[ERROR] [1696782468.213686706]: The node could not connect to the arm. Did you specify the right IP address and is the arm powered on?
terminate called after throwing an instance of 'std::runtime_error'
  what():  not connected !!!
[my_gen3/my_gen3_driver-2] process has died [pid 3256, exit code -6, cmd /home/eftycho/catkin_ws/devel/lib/kortex_driver/kortex_arm_driver __name:=my_gen3_driver __log:=/home/eftycho/.ros/log/9b3bedf2-65f7-11ee-8aa6-c768a5d8440f/my_gen3-my_gen3_driver-2.log].
log file: /home/eftycho/.ros/log/9b3bedf2-65f7-11ee-8aa6-c768a5d8440f/my_gen3-my_gen3_driver-2*.log

**Comment by BourliEftychia** [comment]
Good evening,
I am trying to install the Jackal-kinova robot. I followed the instructions and all the packages were installed without any problem 
I managed to communicate with jackal with a script in python3 and shift him to the desired position. However when I try to run home_robot.py for gen3 lite it throws me this error :
Traceback (most recent call last):
File "home_robot.py", line 7, in
from kortex_driver.msg import ActionNotification, ActionEvent
ModuleNotFoundError: No module named 'kortex_driver'

**Comment by Sungwwoo** [comment]
You need to launch jackal_kinova_moveit_config/Omni_control.launch to start the gazebo simulation 
since 'kortex_driver' is launched in jackal_kinova_moveit_config/Omni_control.launch 

If you want to launch kortex_driver separately. you should put simulation parameters same as[ Omni_control.launch](https://github.com/Sungwwoo/jackal_kinova_simulator/blob/a3e9c3a968d0b7e704e0ef09906c1ec7009f299f/jackal_kinova_moveit_config/launch/Omni_control.launch#L23C1-L23C133) in command line.
